package co.com.kallsony.model;
// Generated 20/10/2013 05:27:07 PM by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Campanna generated by hbm2java
 */

/*
 * 
 * esta es una campaña de kallsony
 * */
@Entity
@Table(name = "CAMPANNA")
public class Campanna implements java.io.Serializable {

	private BigDecimal campannaid;
	private BigDecimal prodid;
	private String url;
	private Date fecIni;
	private Date fecFin;

	public Campanna() {
	}

	public Campanna(BigDecimal campannaid, BigDecimal prodid) {
		this.campannaid = campannaid;
		this.prodid = prodid;
	}
	public Campanna(BigDecimal campannaid, BigDecimal prodid, String url,
			Date fecIni, Date fecFin) {
		this.campannaid = campannaid;
		this.prodid = prodid;
		this.url = url;
		this.fecIni = fecIni;
		this.fecFin = fecFin;
	}

	@Id
	@Column(name = "CAMPANNAID", unique = true, nullable = false, precision = 22, scale = 0)
	@NotNull
	public BigDecimal getCampannaid() {
		return this.campannaid;
	}

	public void setCampannaid(BigDecimal campannaid) {
		this.campannaid = campannaid;
	}

	@Column(name = "PRODID", nullable = false, precision = 22, scale = 0)
	@NotNull
	public BigDecimal getProdid() {
		return this.prodid;
	}

	public void setProdid(BigDecimal prodid) {
		this.prodid = prodid;
	}

	@Column(name = "URL", length = 1000)
	@Length(max = 1000)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FEC_INI", length = 7)
	public Date getFecIni() {
		return this.fecIni;
	}

	public void setFecIni(Date fecIni) {
		this.fecIni = fecIni;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FEC_FIN", length = 7)
	public Date getFecFin() {
		return this.fecFin;
	}

	public void setFecFin(Date fecFin) {
		this.fecFin = fecFin;
	}

}
