package co.com.kallsony.model;
// Generated 20/10/2013 05:27:07 PM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name = "CUSTOMER")
public class Customer implements java.io.Serializable {

	private String custid;
	private String fname;
	private String lname;
	private String phonenumber;
	private String email;
	private String password;
	private String creditcardtype;
	private String creditcardnumber;
	private String status;
	private Set<Orders> orderses = new HashSet<Orders>(0);

	public Customer() {
	}

	public Customer(String custid) {
		this.custid = custid;
	}
	public Customer(String custid, String fname, String lname,
			String phonenumber, String email, String password,
			String creditcardtype, String creditcardnumber, String status,
			Set<Orders> orderses) {
		this.custid = custid;
		this.fname = fname;
		this.lname = lname;
		this.phonenumber = phonenumber;
		this.email = email;
		this.password = password;
		this.creditcardtype = creditcardtype;
		this.creditcardnumber = creditcardnumber;
		this.status = status;
		this.orderses = orderses;
	}

	@Id
	@Column(name = "CUSTID", unique = true, nullable = false, length = 40)
	@NotNull
	@Length(max = 40)
	public String getCustid() {
		return this.custid;
	}

	public void setCustid(String custid) {
		this.custid = custid;
	}

	@Column(name = "FNAME", length = 40)
	@Length(max = 40)
	public String getFname() {
		return this.fname;
	}

	public void setFname(String fname) {
		this.fname = fname;
	}

	@Column(name = "LNAME", length = 40)
	@Length(max = 40)
	public String getLname() {
		return this.lname;
	}

	public void setLname(String lname) {
		this.lname = lname;
	}

	@Column(name = "PHONENUMBER", length = 40)
	@Length(max = 40)
	public String getPhonenumber() {
		return this.phonenumber;
	}

	public void setPhonenumber(String phonenumber) {
		this.phonenumber = phonenumber;
	}

	@Column(name = "EMAIL", length = 40)
	@Length(max = 40)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "PASSWORD", length = 40)
	@Length(max = 40)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "CREDITCARDTYPE", length = 40)
	@Length(max = 40)
	public String getCreditcardtype() {
		return this.creditcardtype;
	}

	public void setCreditcardtype(String creditcardtype) {
		this.creditcardtype = creditcardtype;
	}

	@Column(name = "CREDITCARDNUMBER", length = 40)
	@Length(max = 40)
	public String getCreditcardnumber() {
		return this.creditcardnumber;
	}

	public void setCreditcardnumber(String creditcardnumber) {
		this.creditcardnumber = creditcardnumber;
	}

	@Column(name = "STATUS", length = 10)
	@Length(max = 10)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customer")
	public Set<Orders> getOrderses() {
		return this.orderses;
	}

	public void setOrderses(Set<Orders> orderses) {
		this.orderses = orderses;
	}

}
