package co.com.kallsony.model;
// Generated 20/10/2013 05:27:07 PM by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Items generated by hbm2java
 */
@Entity
@Table(name = "ITEMS")
public class Items implements java.io.Serializable {

	private String itemid;
	private Orders orders;
	private BigDecimal prodid;
	private String productname;
	private String partnum;
	private BigDecimal price;
	private Integer quantity;

	public Items() {
	}

	public Items(String itemid, Orders orders) {
		this.itemid = itemid;
		this.orders = orders;
	}
	public Items(String itemid, Orders orders, BigDecimal prodid,
			String productname, String partnum, BigDecimal price,
			Integer quantity) {
		this.itemid = itemid;
		this.orders = orders;
		this.prodid = prodid;
		this.productname = productname;
		this.partnum = partnum;
		this.price = price;
		this.quantity = quantity;
	}

	@Id
	@Column(name = "ITEMID", unique = true, nullable = false, length = 10)
	@NotNull
	@Length(max = 10)
	public String getItemid() {
		return this.itemid;
	}

	public void setItemid(String itemid) {
		this.itemid = itemid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ORDID", nullable = false)
	@NotNull
	public Orders getOrders() {
		return this.orders;
	}

	public void setOrders(Orders orders) {
		this.orders = orders;
	}

	@Column(name = "PRODID", precision = 22, scale = 0)
	public BigDecimal getProdid() {
		return this.prodid;
	}

	public void setProdid(BigDecimal prodid) {
		this.prodid = prodid;
	}

	@Column(name = "PRODUCTNAME", length = 200)
	@Length(max = 200)
	public String getProductname() {
		return this.productname;
	}

	public void setProductname(String productname) {
		this.productname = productname;
	}

	@Column(name = "PARTNUM", length = 20)
	@Length(max = 20)
	public String getPartnum() {
		return this.partnum;
	}

	public void setPartnum(String partnum) {
		this.partnum = partnum;
	}

	@Column(name = "PRICE", precision = 9)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@Column(name = "QUANTITY", precision = 9, scale = 0)
	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

}
