package co.com.kallsony.model;
// Generated 20/10/2013 05:27:07 PM by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Orders generated by hbm2java
 */
@Entity
@Table(name = "ORDERS")
public class Orders implements java.io.Serializable {

	private String ordid;
	private Customer customer;
	private Date orderdate;
	private BigDecimal price;
	private String status;
	private String comments;
	private Set<Items> itemses = new HashSet<Items>(0);

	public Orders() {
	}

	public Orders(String ordid, Customer customer) {
		this.ordid = ordid;
		this.customer = customer;
	}
	public Orders(String ordid, Customer customer, Date orderdate,
			BigDecimal price, String status, String comments, Set<Items> itemses) {
		this.ordid = ordid;
		this.customer = customer;
		this.orderdate = orderdate;
		this.price = price;
		this.status = status;
		this.comments = comments;
		this.itemses = itemses;
	}

	@Id
	@Column(name = "ORDID", unique = true, nullable = false, length = 10)
	@NotNull
	@Length(max = 10)
	public String getOrdid() {
		return this.ordid;
	}

	public void setOrdid(String ordid) {
		this.ordid = ordid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CUSTID", nullable = false)
	@NotNull
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ORDERDATE", length = 7)
	public Date getOrderdate() {
		return this.orderdate;
	}

	public void setOrderdate(Date orderdate) {
		this.orderdate = orderdate;
	}

	@Column(name = "PRICE", precision = 9)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@Column(name = "STATUS", length = 10)
	@Length(max = 10)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "COMMENTS", length = 4000)
	@Length(max = 4000)
	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orders")
	public Set<Items> getItemses() {
		return this.itemses;
	}

	public void setItemses(Set<Items> itemses) {
		this.itemses = itemses;
	}

}
